# show multiple downstream steps consuming the same parent

[[step]]
name = "start"
script = '''
echo "banana" > $OUTPUT_DIR/upper
echo "banana" > $OUTPUT_DIR/sort
'''

[[step]]
name = "upper"
inputs = ["upper"]
script = '''
tr '[:lower:]' '[:upper:]' < $INPUT_FILE > $OUTPUT_DIR/done
'''

[[step]]
name = "sort"
inputs = ["sort"]
script = '''
sort < $INPUT_FILE > $OUTPUT_DIR/done
'''
